// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsTZJ8wRhqaCFmTqLcniExSEZ6BFKEQ_M',
    appId: '1:253244579790:web:92e9e567955a86625a959f',
    messagingSenderId: '253244579790',
    projectId: 'wallpaper-app-a5731',
    authDomain: 'wallpaper-app-a5731.firebaseapp.com',
    storageBucket: 'wallpaper-app-a5731.firebasestorage.app',
    measurementId: 'G-CZ4EMRFC4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0WXNbHG4CIIT2R0IZIXQLx9TNp3Nvy8',
    appId: '1:253244579790:android:880e27bdacc70caa5a959f',
    messagingSenderId: '253244579790',
    projectId: 'wallpaper-app-a5731',
    storageBucket: 'wallpaper-app-a5731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-mwf3vjh0c3WIrzWAzhPWf8I3DecvOg',
    appId: '1:253244579790:ios:718f24526e4749fe5a959f',
    messagingSenderId: '253244579790',
    projectId: 'wallpaper-app-a5731',
    storageBucket: 'wallpaper-app-a5731.firebasestorage.app',
    iosClientId: '253244579790-oqat237k0uq31bdub5gei2b2fjeb18c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4-mwf3vjh0c3WIrzWAzhPWf8I3DecvOg',
    appId: '1:253244579790:ios:718f24526e4749fe5a959f',
    messagingSenderId: '253244579790',
    projectId: 'wallpaper-app-a5731',
    storageBucket: 'wallpaper-app-a5731.firebasestorage.app',
    iosClientId: '253244579790-oqat237k0uq31bdub5gei2b2fjeb18c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsTZJ8wRhqaCFmTqLcniExSEZ6BFKEQ_M',
    appId: '1:253244579790:web:175cb12f28b720195a959f',
    messagingSenderId: '253244579790',
    projectId: 'wallpaper-app-a5731',
    authDomain: 'wallpaper-app-a5731.firebaseapp.com',
    storageBucket: 'wallpaper-app-a5731.firebasestorage.app',
    measurementId: 'G-11G4SPXVP4',
  );

}